curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/accessibility.5a528201.chunk.min.js.map' > accessibility.5a528201.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/accessibilityBrowserZoom.6895cb62.chunk.min.js.map' > accessibilityBrowserZoom.6895cb62.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/animations.49c55ede.chunk.min.js.map' > animations.49c55ede.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/animationsWixCodeSdk.726e9885.chunk.min.js.map' > animationsWixCodeSdk.726e9885.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/appMonitoring.d502493c.chunk.min.js.map' > appMonitoring.d502493c.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/assetsLoader.1a4bd352.chunk.min.js.map' > assetsLoader.1a4bd352.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/browser-deprecation.bundle.es5.js.map' > browser-deprecation.bundle.es5.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/businessLogger.382014f6.chunk.min.js.map' > businessLogger.382014f6.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/componentsLoader.07f88113.chunk.min.js.map' > componentsLoader.07f88113.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/consentPolicy.c7f0149b.chunk.min.js.map' > consentPolicy.c7f0149b.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/contentReflow.e4dd8a93.chunk.min.js.map' > contentReflow.e4dd8a93.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/cyclicTabbing.7085d18c.chunk.min.js.map' > cyclicTabbing.7085d18c.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/domSelectors.0df2cf2d.chunk.min.js.map' > domSelectors.0df2cf2d.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/domStore.4d54a74d.chunk.min.js.map' > domStore.4d54a74d.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/dynamicPages.1b10d791.chunk.min.js.map' > dynamicPages.1b10d791.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/environment.aa72590f.chunk.min.js.map' > environment.aa72590f.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/environmentService.ce65c260.chunk.min.js.map' > environmentService.ce65c260.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/environmentWixCodeSdk.dbb376f6.chunk.min.js.map' > environmentWixCodeSdk.dbb376f6.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/externalServices.bf1ce5f4.chunk.min.js.map' > externalServices.bf1ce5f4.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_0.5120b1c2.chunk.min.js.map' > group_0.5120b1c2.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_11.e2f9d796.chunk.min.js.map' > group_11.e2f9d796.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_14.71cad7d9.chunk.min.js.map' > group_14.71cad7d9.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_2.4cb4d010.chunk.min.js.map' > group_2.4cb4d010.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_20.1128a55d.chunk.min.js.map' > group_20.1128a55d.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_23.572bd6dc.chunk.min.js.map' > group_23.572bd6dc.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_24.ae2b90b3.chunk.min.js.map' > group_24.ae2b90b3.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_27.24507aab.chunk.min.js.map' > group_27.24507aab.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_28.98f4bda8.chunk.min.js.map' > group_28.98f4bda8.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_3.443a1623.chunk.min.js.map' > group_3.443a1623.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_30.2abbdf6f.chunk.min.js.map' > group_30.2abbdf6f.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_32.643a5cba.chunk.min.js.map' > group_32.643a5cba.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_36.bc4eabb9.chunk.min.js.map' > group_36.bc4eabb9.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_38.90c9557b.chunk.min.js.map' > group_38.90c9557b.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_4.825d1a51.chunk.min.js.map' > group_4.825d1a51.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_42.825d0e24.chunk.min.js.map' > group_42.825d0e24.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_5.79f06044.chunk.min.js.map' > group_5.79f06044.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_6.8fc8a69c.chunk.min.js.map' > group_6.8fc8a69c.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_7.c0d47db2.chunk.min.js.map' > group_7.c0d47db2.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/group_9.c8b7529f.chunk.min.js.map' > group_9.c8b7529f.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/imagePlaceholder.a5c38083.chunk.min.js.map' > imagePlaceholder.a5c38083.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/main.bd1e9da6.bundle.min.js.map' > main.bd1e9da6.bundle.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/main.renderer.99fa8096.bundle.min.js. > main.renderer.99fa8096.bundle.min.jsmap'
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/mobileFullScreen.3c69b7f5.chunk.min.js.map' > mobileFullScreen.3c69b7f5.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/motion.4dedec96.chunk.min.js.map' > motion.4dedec96.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/mpaNavigation.a6072a7b.chunk.min.js.map' > mpaNavigation.a6072a7b.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/multilingual.656b9723.chunk.min.js.map' > multilingual.656b9723.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/navigation.857097f4.chunk.min.js.map' > navigation.857097f4.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/onloadCompsBehaviors.7e1bb591.chunk.min.js.map' > onloadCompsBehaviors.7e1bb591.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/ooi.5da71659.chunk.min.js.map' > ooi.5da71659.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/pageAnchors.b16478c5.chunk.min.js.map' > pageAnchors.b16478c5.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/panorama.1bdf1744.chunk.min.js.map' > panorama.1bdf1744.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/platform.884c7fe8.chunk.min.js.map' > platform.884c7fe8.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/platformPubsub.bde4edad.chunk.min.js.map' > platformPubsub.bde4edad.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/popups.4f64a536.chunk.min.js.map' > popups.4f64a536.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/protectedPages.9e2f0c3d.chunk.min.js.map' > protectedPages.9e2f0c3d.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/renderer.90f3ef29.chunk.min.js.map' > renderer.90f3ef29.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/reporter-api.b7edb858.chunk.min.js. > reporter-api.b7edb858.chunk.min.jsmap'
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/router.a868afca.chunk.min.js.map' > router.a868afca.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/routerFetch.4fed4805.chunk.min.js.map' > routerFetch.4fed4805.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/scrollToAnchor.c63ab772.chunk.min.js.map' > scrollToAnchor.c63ab772.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/siteMembers.4f6f476c.chunk.min.js.map' > siteMembers.4f6f476c.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/siteMembersWixCodeSdk.c31eca95.chunk.min.js.map' > siteMembersWixCodeSdk.c31eca95.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/siteScrollBlocker.d38ddc5a.chunk.min.js.map' > siteScrollBlocker.d38ddc5a.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/speculationRules.0f29966f.chunk.min.js.map' > speculationRules.0f29966f.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/ssrCache.a72bfdc3.chunk.min.js.map' > ssrCache.a72bfdc3.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/stores.0468e03d.chunk.min.js.map' > stores.0468e03d.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/svgLoader.dda061e2.chunk.min.js.map' > svgLoader.dda061e2.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/thunderbolt-commons.2f177949.bundle.min.js. > thunderbolt-commons.2f177949.bundle.min.jsmap'
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/thunderbolt-components-registry.2b110099.chunk.min. > thunderbolt-components-registry.2b110099.chunk.minjs.map'
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/triggersAndReactions.23ab777e.chunk.min.js.map' > triggersAndReactions.23ab777e.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/tslib.inline.ca2949bb.chunk.min.js. > tslib.inline.ca2949bb.chunk.min.jsmap'
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/usedPlatformApis.b09c4d5c.chunk.min.js.map' > usedPlatformApis.b09c4d5c.chunk.min.js.map
curl 'https://static.parastorage.com/services/wix-thunderbolt/dist/windowScroll.b6975c2a.chunk.min.js.map' > windowScroll.b6975c2a.chunk.min.js.map